BotQQ: 123
HostQQ: 123
miraiHost: http://localhost:8080
authKey: !!str 1234567890
DBLink: sqlite:///data.db
setuPath: M:\Pixiv\pxer_new\
setu18Path: M:\Pixiv\pxer18_new\
realPath: M:\Pixiv\reality\
realHighqPath: M:\Pixiv\reality\highq\
wallpaperPath: M:\Pixiv\bizhi\highq\
sketchPath: M:\线稿\
txAppId: !!str 1234567890
txAppKey: ABCDEFGHIJKLMN
shadiaoAppName: shadiao
saucenaoCookie: balabala
webManagerApi: true
webManagerAutoBoot: true
