BotQQ: 123
HostQQ: 123
miraiHost: http://localhost:8080
authKey: !!str 1234567890
DBLink: sqlite+aiosqlite:///data.db
setuPath: M:\Pixiv\pxer_new\
setu18Path: M:\Pixiv\pxer18_new\
realPath: M:\Pixiv\reality\
realHighqPath: M:\Pixiv\reality\highq\
wallpaperPath: M:\Pixiv\bizhi\highq\
sketchPath: M:\线稿\
txAppId: !!str 1234567890
txAppKey: ABCDEFGHIJKLMN
shadiaoAppName: shadiao
saucenaoApiKey: balabala
webManagerApi: true
webManagerAutoBoot: true
errorRetention: 14
commonRetention: 7
loliconApiKey: loliconApiKey
loliconImageCache: true
networkDataCache: true
wolframAlphaKey: wolframAlphaKey
proxy: proxy_url
automaticUpdate: false