# 构建 Docker 镜像
name: Docker Image CI

# 触发条件
on:
  push:
    tags:       # Tags更新时触发此workflow
      - '*'

# 工作流程
jobs:

  build:
    # 运行环境
    runs-on: ubuntu-latest
    # 运行步骤
    steps:
    
    # 检出（仓库）文件 / 获取代码
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: ls -la --color
      
    # 登录 docker Hub
    - name: Login Docker Hub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_TOKEN}}
    
    # 镜像元数据操作
    - name: Docker Metadata action
      id: meta
      uses: docker/metadata-action@v4.0.1
      with:
        # 覆写一些默认的元数据LABELS
        labels: |
          MAINTAINER=zaphakiel
          org.opencontainers.image.title=sagiri-bot
          org.opencontainers.image.description=基于Graia Ariadne和Mirai的QQ机器人 SAGIRI-BOT
          org.opencontainers.image.url=https://github.com/SAGIRI-kawaii/sagiri-bot
          org.opencontainers.image.source=https://github.com/SAGIRI-kawaii/sagiri-bot
        images: |
          zaphakiel/sagiri-bot
    
    # 构建 并 推送镜像
    - name: build and push docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
